bon eval
allenai/reward-bench pull request #111
Opened 2024-04-20 10:55 UTC by yuchenlin

2024-04-22 16:13 UTC, natolambert commented
Will give a more thorough review once the data is moved.
You can use the function `save_to_hub` to easily do this.
Would be good to just add the data conversion scripts in the source `rewardbench/` repo, then call them in the script so it's all automatic end to end.

2024-04-25 15:58 UTC, natolambert requested changes
This is getting closer. High level comments also shared on slack.
1. We still have more jsons to move to huggingface
2. Make all of this happen in the existing `scripts/run_bon.py`. 
3. To do so, most of the functions can be in `rewardbench/bon_utils.py`
4. We can have duplicated scripts in analysis in case there's an error and someone wants to re-run alpacaeval conversion
5. Code cleaning, adding license, removing unnecessary things

Mostly, I want to make this first-party supported in the repo, not a separate folder.

2024-04-30 14:10 UTC, yuchenlin commented on bon_eval/bon_utils.py
> +from alpaca_eval import analyze, annotators, constants, decoders, metrics, utils
In the new commits, I've removed unnecessary imports, the kept ones are all needed in this script.

2024-04-30 14:11 UTC, yuchenlin commented on bon_eval/bon_utils.py
> +if __name__ == "__main__":
it was used for testing and showing the usage. now it's not useful and I've removed it

2024-04-30 14:12 UTC, yuchenlin commented on bon_eval/bon_utils.py
> +def evaluate(
added a comment: # modified from https://github.com/tatsu-lab/alpaca_eval/blob/c4a4ca716b4cab46701af759c244cb9d05772e15/src/alpaca_eval/main.py#L17C5-L17C5

2024-09-26 22:06 UTC, closed without merging